[export]
db-type="mysql"
ip="192.168.3.61"
port="3306"
username="root"
password="admin"
db-name="swa-demo"
config="charset=utf8mb4&parseTime=True&loc=Local"

[import]
db-type="mysql"
ip="192.168.3.61"
port="3306"
username="root"
password="12345"
db-name="go-swa"
config="charset=utf8mb4&parseTime=True&loc=Local"

[tables]
table-string="casbin_rule,swa_apis,swa_blacklist,swa_btn_role,swa_btns,swa_dict_details,swa_dicts,swa_menu_param,swa_menu_role,swa_menus,swa_role_apis,swa_role_menus,swa_role_subroles,swa_role_users,swa_roles,swa_user_role,swa_users"
